vich_uploader:
    db_driver: orm
    
    metadata:
        type: attribute
    
    mappings:
        images_background:
            uri_prefix: '%images_background%'
            upload_destination: '%kernel.project_dir%/public%images_background%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
